name: Node.js Deployment with NGINX and SSL

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |

            cd /var/www/html/saas/admin
            git fetch --all
            git reset --hard origin/main

            if [ ! -f .env ]; then
              cp .env.example .env
            fi
            npm install
            npm run build
            cp -r build/* /var/www/html/admin/
            sudo systemctl restart nginx
